### ISSUE TITLE
Does not work in new Firefox version (v57)

### ISSUE THREAD

**Issue by derTobsch** [NicolasBonduel/Google-Music-Control#2]
The new Add-On api is not provided, but this is a great Add-On. Do you plan to update it to the new api?

If now, would you add a licence like MIT so I can fork it?

**Comment by lidel** [comment]
@derTobsch if you are looking for something that works under Firefox 57+, 
I wrote this from scratch: https://github.com/lidel/google-music-hotkeys

**Comment by derTobsch** [comment]
@lidel I am using yours now, but I would like to set my own shortcuts. Could you add this feature?

**Comment by NicolasBonduel** [comment]
I'm sorry @derTobsch I'm not using Google Music anymore and I'm not too familiar with the new addon api yet.
Of course you can fork it! I will add a license asap. If you open a pull request I would be glad to review it ;)

EDIT: Added the MIT License ;)

**Comment by lidel** [comment]
@derTobsch see https://github.com/lidel/google-music-hotkeys/issues/1#issuecomment-344328280

**Comment by derTobsch** [comment]
Lets close this and lets use the extension from lidel :)
